### ISSUE TITLE
No matching distribution for tf

### ISSUE THREAD

**Issue by dmoonat** [AlexElvers/stplfcnn#1]
Trying to install with pip 

![image](https://user-images.githubusercontent.com/25177773/101760551-03d18180-3b01-11eb-9797-4c13599d3e41.png)

**Comment by marcus-voss** [comment]
Mh. Given that TF has changed lot since then (given the integration of Keras), it may be that they don't have the version on PyPI anymore. But I'm sure there is a way to manually install a TF version that satisfies the requirement.

**Comment by dmoonat** [comment]
Okay, will try to install it manually.

**Comment by dmoonat** [comment]
Hey @marcus-voss 
I am still not able to install 1.8, tried installing from whl but it is not working 

![image](https://user-images.githubusercontent.com/25177773/101768609-cde5ca80-3b0b-11eb-8b0d-79d0cab3e3d8.png)

**Comment by marcus-voss** [comment]
I assume you have a Linux with 64 bit? Just to make sure.
I'm happy to support you getting it to run, but have no specific insights into how get older TF version. Unless @AlexElvers happens to know something, I can try myself on the weekend.

**Comment by dmoonat** [comment]
I assume you have a Linux with 64 bit?  Yes
Sure,Let me know if there is any work-around.
Thanks!

**Comment by marcus-voss** [comment]
One possibility, but I guess that depends on your skills with TF, would be to migrate it to TF 2.0. See for instance:
- https://www.tensorflow.org/guide/migrate
- https://www.tensorflow.org/guide/upgrade
I once did this for a script, and it can be as simple as changing some imports, but may also need some manual adjustments.

**Comment by AlexElvers** [comment]
Hey @dmoonat!
I would guess that you are using a Python version that is not compatible with the wheel. The wheel is compiled for Python 3.6 (the filename contains 'cp36'). Unfortunately, more recent versions of Python cannot be used for TensorFlow 1.8.
In Python 3.6, installing the TensorFlow wheel from https://pypi.org/project/tensorflow/1.8.0/#files (tensorflow-1.8.0-cp36-cp36m-manylinux1_x86_64.whl) works on my computer.

**Comment by dmoonat** [comment]
Hey @AlexElvers 
It works!

![image](https://user-images.githubusercontent.com/25177773/101872511-61220d00-3bab-11eb-9ad0-973c7931409b.png)


@AlexElvers @marcus-voss  Thanks for the help!

**Comment by dmoonat** [comment]
One more thing, how we can run it for custom dataset?changes needed?

Or sample params file for STLQFCNNEstimator?

**Comment by AlexElvers** [comment]
Hey!
Using this [data loader config](https://github.com/AlexElvers/stplfcnn/blob/master/example/params/data_readers/boulder-H-agg_10-10_1.yaml), you can load data from `data/pecanstreet/boulder/H/boulder_H_load_agg_10.csv`. The data should look as follows:
```
$ head -n3 data/pecanstreet/boulder/H/boulder_H_load_agg_10.csv 
,10_1,10_2
2015-01-01 00:00:00-07:00,5.657,9.287
2015-01-01 01:00:00-07:00,8.052,8.347
```
The corresponding weather data is loaded from `data/pecanstreet/boulder/boulder_weather.csv`:
```
$ head -n3 data/pecanstreet/boulder/boulder_weather.csv 
,temperature,apparent_temperature,dew_point,humidity,visibility,pressure,wind_speed,cloud_cover,wind_bearing,precip_intensity,precip_probability
2015-01-01 00:00:00-07:00,-12.86,-17.07,-1.67,0.61,10.00,1029.59,4.04,0.05,245.00,0.00,0.00
2015-01-01 01:00:00-07:00,-13.44,-18.17,-2.50,0.62,10.00,1028.76,4.54,0.02,242.00,0.00,0.00
```

If you are using a different format, you can add a custom data loader class. The return value of `read_data` should be a DataFrame with timestamp as index, one column named 'load' containing load data and weather (or other) data in the other columns.

Here is an example for an estimator config that also might help you:
```
type: STLQFCNNEstimator
time_horizon: !ref 'hor-24h-H'
quantile_levels: !ref 'q-7'
history_shape: [7, 24]
conv_layers_params:
- filter_shape: [5, 5]
  num_filters: 26
  pooling_shape: [1, 2]
fc_layers_params:
- {activation: relu, num_outputs: 100}
- {activation: relu, num_outputs: 82}
- {}
historical_inputs: []
horizon_inputs: [temperature]  # this will use the temperature column of the DataFrame
```

**Comment by dmoonat** [comment]
Hey, Thanks for sharing this info!
But i guess the data folder,files are missing from repo

**Comment by marcus-voss** [comment]
Yes, we can't upload the data there. You will have to get a license from Pecan street. Unfortunately, they by now changed their licensing and made the data unavailable for free even for academics at the beginning of 2020. Now, you need an expensive license, or you can only get a smaller subset than the one we used.

**Comment by dmoonat** [comment]
Okay,No Worries!

@AlexElvers @marcus-voss Thanks for the continuous support!
Great approach to probabilistic forecasting!
Kudos to the team!

PS:[Closing this issue,will connect if have any other questions]
